### ISSUE TITLE
Plotly required when running on command line

### ISSUE THREAD

**Issue by elementechemlyn** [nhs-bnssg-analytics/PathSimR#1]
I'm running the application from the command line (in Debian Bullseye) and was required to install the package plotly which is not listed in the install packages section at the start of the script. i.e.

install.packages("plotly")

I'm guessing that's only a requirement when running outside of RStudio?

**Comment by benmurch** [comment]
This is happening because there are two calls to load the plotly library within the code. If you do not have it installed already, you will need to install it, regardless of whether you are running it in R Studio.

I believe that the inclusion of the calls to plotly are a legacy issue (i.e. plotly was used in an earlier version of the software but subsequently dropped, and removed from the list of packages which you need to install, but the library call was left in). I will revise the code on github once I’ve tested this. For the timebeing, you can either install plotly, or remove the library calls within the script (lines 4201 and 4451) – I’ve checked this and it will work.
